<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fontys Cyber Security</title>
    <?php
    include("../components/navigation-pages.php");
    ?>
    <link rel="stylesheet" href="template.css">
</head>

<body>
    <header>
        <h1>Identity Management, Authentication and Access Control</h1>
    </header>

    <div class="container">

        <p>
            For this topic I will be covering Identity Management, Authentication and Access Control. This topic will be different. After our lecture at university,
            me and my group stayed and crafted an example role structure and policies for the DigiD dutch identity management platform. Sadly me and my group lost the original diagram that we created at university. Since I couldn't show our image, I will be explaining the steps of the identity platform with a diagram which we took ideas from when creating ours. This is the link I used <a href="https://www.logius.nl/domeinen/toegang/digid/documentatie/koppelvlakspecificatie-digid-saml-authenticatie">Koppelvlakspecificatie DigiD SAML Authenticatie</a>. Here's what we did and the explanation of it:
        </p>


        <div class="image">
            <img src="../assets/identity/diagram.png" alt="intro">
        </div>

        <div class="bullet">
            <ul>
                <li><b>Step 1:</b> The end user with a browser as User Agent (UA) wants to use the service provider's web service.
                </li>

                <li><b>Step 2:</b> The service provider wants to establish the identity of the end user. The web service therefore forwards the end user to DigiD. The web service hereby asks for the minimum desired assurance level with which the end user must authenticate with DigiD.
                </li>

                <li><b>Step 3 & 4:</b> The end user is presented with the DigiD login screen and authenticates with one of the available logins means at the minimum desired assurance level.
                </li>

                <li><b>Step 5:</b> DigiD sends the end user back to the web service via a redirect. Here a meaningless Artifact generated by DigiD is sent along. This Artifact refers to the actual SAML message that is subsequently exchanged via the back channel in steps 6 and 7.
                </li>

                <li><b>Step 6:</b> The web service establishes a secure connection with DigiD via the back channel and sends an Artifact Resolve message containing the SAML Artifact.
                </li>

                <li><b>Step 7:</b> DigiD immediately replies with the Artifact Response message that belongs to the SAML Artifact. In this message, DigiD provides the Assertion, including the authentication result and, if authentication is successful, the BSN (sectoral number) of the end user.
                </li>

                <li><b>Step 8:</b> The service provider processes the Assertion from the DigiD authentication message, thus establishing the identity of the end user. Only with successful authentication will the end user gain access to the service provider's web service.
                </li>


            </ul>
        </div>


        <div class="subtheme">Afterthoughts</div>

        <p>
            This topic wasn't very thourough, but mine and other groups covered this at university. So this isn't only my words and toughts, but a combination of their ideas as well. Identity Management, Authentication and Access control are critical to any comprehensive and secure tool that operates with user accounts. These subjects have
            been in the OWASP top 10 the the last 20 years.
        </p>

        <div class="image">
            <img src="../assets/identity/conclusion.png" alt="intro">
        </div>
        
        <p>
            As you can see broken access control hasn't moved from the second spot since 2019. By implementing strong authentication measures and carefully controlling access to sensitive resources, the project can significantly reduce the risk of a data breach or cyberattack. It is the cornerstone of any application/device's security.
        </p>
    
</body>
</html>